name = "NoLib"
uuid = "87179f8f-7bad-4647-abf4-d65b80753c8f"
authors = ["Winant Pablo <pablo.winant@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
